<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Label="EF Core">
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="MySqlConnector" Version="2.6.0" />
    <PackageVersion Include="Oracle.ManagedDataAccess" Version="23.26.200" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup Label="Caching">
    <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="10.4.0" />
  </ItemGroup>
  <ItemGroup Label="Logging">
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup Label="API Docs">
    <PackageVersion Include="Scalar.AspNetCore" Version="2.13.14" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>
</Project>